# Generated by Django 2.2.2 on 2019-06-19 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20190619_1228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('entry_fee', models.DecimalField(decimal_places=2, help_text='Amount user must send to eligible user', max_digits=8, verbose_name='Entry fee')),
                ('level_reward', models.DecimalField(decimal_places=2, help_text='Amount users will receive', max_digits=8, verbose_name='Level reward')),
            ],
            options={
                'verbose_name': 'level',
                'verbose_name_plural': 'levels',
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='amount_received',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Amount received'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='amount_sent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Amount sent'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='karma',
            field=models.FloatField(default=10),
        ),
        migrations.AddField(
            model_name='customuser',
            name='task',
            field=models.CharField(choices=[('S', 'Send funding'), ('R', 'Receive funding')], default='S', max_length=2),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='level',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Level'),
        ),
    ]
