# Generated by Django 2.2.3 on 2019-07-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_transactionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionlog',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
