# Generated by Django 2.2.3 on 2019-07-20 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20190718_1455'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='peer',
            unique_together={('user_from', 'user_to')},
        ),
    ]
